In [1]:
import diversampling as ds

In [2]:
import pandas as pd
# read data
data = pd.read_csv('creditcard_csv.csv')
data = data.drop(columns=['Time'], axis=0)
data.Class = data.Class.str[1]
# data cleaning (数据dataframe转换成array并增加index，分离标签)
display(data.head(5))
arr = data.to_numpy()
arr[:, -1] = arr[:, -1].astype(int)
arr_x = arr[:, :-1]
arr_y = arr[:, -1]

V1        V2        V3        V4        V5        V6        V7  \
0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9       V10  ...       V21       V22       V23       V24  \
0  0.098698  0.363787  0.090794  ... -0.018307  0.277838 -0.110474  0.066928   
1  0.085102 -0.255425 -0.166974  ... -0.225775 -0.638672  0.101288 -0.339846   
2  0.247676 -1.514654  0.207643  ...  0.247998  0.771679  0.909412 -0.689281   
3  0.377436 -1.387024 -0.054952  ... -0.108300  0.005274 -0.190321 -1.175575   
4 -0.270533  0.817739  0.753074  ... -0.009431  0.798278 -0.137458  0.141267   

        V25       V26       V27       V28  Amount  Class  
0  0.128539 -0.189115  0.133558 -0.021053  149.62      0  
1  0.167170  0.125895 -0.008983  0.014724    2.69      0  
2 -0.327642 -0.139097 -0.055353 -0.059752  378.66      0  
3  0.647376 -0.221929  0.062723  0.061458  123.50      0  
4 -0.206010  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 30 columns]

# Brief Version

In [ ]:
x = ds.Sample_data(arr_x, decreasing_ratio_threshold=0.005)
clustering = ds.cluster_process(x, cl_upper_num=50, accum_wcss_drop_ratio_threshold=0.02)
y = ds.Sample_label(arr_y)
usampling = ds.under_sampling(x, y, clustering.cluster_label, under_sampling_multiplier=2, random_multiplier = 0.05, n_neighbors=None)
display(usampling.array_under_sampled_final)    #final sample set after under-sampling
usampling.final_stats()    #sample balance stats of final dataset

# Complete Version

In [3]:
# Instantiation of sample's x
x = ds.Sample_data(arr_x, decreasing_ratio_threshold=0.005)
x.scaler    #data after scaling process 

array([[-2.41068457e-02, -1.00090002e-03,  5.24845485e-02, ...,
         4.22490003e-03, -6.21991639e-04,  5.82379309e-03],
       [ 2.11294049e-02,  3.66015333e-03,  3.44496809e-03, ...,
        -2.84165597e-04,  4.35011014e-04,  1.04705276e-04],
       [-2.40810855e-02, -1.84301680e-02,  3.66929688e-02, ...,
        -1.75099479e-03, -1.76530902e-03,  1.47389219e-02],
       ...,
       [ 3.40303095e-02, -4.14289805e-03, -6.72447011e-02, ...,
         1.40919405e-04, -7.84713406e-04,  2.64215395e-03],
       [-4.26255389e-03,  7.29529265e-03,  1.45370235e-02, ...,
         3.44236533e-03,  3.08831881e-03,  3.89238944e-04],
       [-9.45640971e-03, -2.60924759e-03,  1.45541395e-02, ...,
        -7.64043295e-05,  4.03243673e-04,  8.44648509e-03]])

In [4]:
display(x.pca_table.head(5))    #pca process stats
print('pca_var_num is ', x.pca_var_num)    #final dimensionality number

component_no  explain_ratio  ratio_diff
0             1       0.151364         NaN
1             2       0.297249    0.145885
2             3       0.432701    0.135451
3             4       0.531544    0.098843
4             5       0.614048    0.082504

pca_var_num is  18


In [5]:
display(x.pca_array)    #data after pca process
x.pca_model    #pca model

array([[-0.13910472, -0.05376718,  0.0145995 , ...,  0.02324513,
        -0.00816234, -0.05267923],
       [ 0.06862548,  0.03579341, -0.07412982, ..., -0.02153518,
         0.00452342, -0.00330137],
       [ 0.10065131, -0.03954886, -0.15034289, ...,  0.0243945 ,
        -0.04404826, -0.03606401],
       ...,
       [-0.02577535, -0.02484009,  0.13962852, ..., -0.0324645 ,
        -0.01261141,  0.06802538],
       [-0.1462211 ,  0.15542192,  0.02687139, ...,  0.00373276,
        -0.02023228, -0.01490194],
       [-0.02638959, -0.23263892,  0.00192067, ...,  0.009373  ,
         0.02627175, -0.01435002]])

PCA(n_components=18)

In [6]:
# Instantiation of sample's y(label)
y = ds.Sample_label(arr_y)
y.stats    #label stats summary

C:\Users\zhu92\Coding\diversampling\undersampling.py:39: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  return pd.Series(data).value_counts().append(pd.Series({'total':len(data), 'minority_percentage(%)':round(pd.Series(data).value_counts().min()/len(data)*100, 3)}))


0                         284315.000
1                            492.000
total                     284807.000
minority_percentage(%)         0.173
dtype: float64

In [7]:
# Instantiation of the unsupervised classification process
clustering = ds.cluster_process(x, cl_upper_num=50, accum_wcss_drop_ratio_threshold=0.02)
display(clustering.kms_table.head(5))    #kmeans process stats table
print('The proper cluster number is ', clustering.cluster_num)    #final unsupervised cluster number 

C:\Users\zhu92\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\cluster\_kmeans.py:1934: FutureWarning: The default value of `n_init` will change from 3 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=3)
C:\Users\zhu92\AppData\Local\Programs\Python\Python39\lib\site-packages\joblib\externals\loky\backend\context.py:136: UserWarning: Could not find the number of physical cores for the following reason:
found 0 physical cores < 1
Returning the number of logical cores instead. You can silence this warning by setting LOKY_MAX_CPU_COUNT to the number of cores you want to use.
  warnings.warn(
  File "C:\Users\zhu92\AppData\Local\Programs\Python\Python39\lib\site-packages\joblib\externals\loky\backend\context.py", line 282, in _count_physical_cores
    raise ValueError(f"found {cpu_count_physical} physical cores < 1")


cluster          wcss    wcss_diff  wcss_drop_rate  wcss_drate_2rolling_sum
0        2  32733.923796          NaN             NaN                      NaN
1        3  30167.612227 -2566.311569       -0.134147                      NaN
2        4  28439.711733 -1727.900494       -0.090322                -0.224469
3        5  27121.798586 -1317.913147       -0.068890                -0.159212
4        6  26525.275469  -596.523118       -0.031182                -0.100072

The proper cluster number is  14


In [8]:
display(clustering.cluster_label)    #cluster label for data
clustering.kms_model    #kmeans model

array([[8],
       [9],
       [5],
       ...,
       [6],
       [3],
       [1]])

MiniBatchKMeans(batch_size=256, n_clusters=14, random_state=7)

In [9]:
clustering.cluster_stats    #cluster stats information

cluster  counts  percentage(%)
0         0   21707           7.62
1         1   22942           8.06
2         2   21046           7.39
3         3   12009           4.22
4         4   17111           6.01
5         5   12951           4.55
6         6   31065          10.91
7         7   21310           7.48
8         8   26224           9.21
9         9   23537           8.26
10       10   15395           5.41
11       11   14548           5.11
12       12   27509           9.66
13       13   17453           6.13

In [10]:
# Instantiation of the under-sampling process
usampling = ds.under_sampling(x, y, clustering.cluster_label, under_sampling_multiplier=2, random_multiplier = 0.05, n_neighbors=None)
usampling.cat_stat_tab    #cluster across label groupby results

cluster no.  Majority counts  U-sampled Majority counts  Minority counts
0             0            21699                         22                8
1             1            22905                        240               37
2             2            21039                         98                7
3             3            11798                        467              211
4             4            17081                         94               30
5             5            12907                         91               44
6             6            31058                         63                7
7             7            21278                        136               32
8             8            26181                        198               43
9             9            23528                         19                9
10           11            14511                        143               37
11           12            27488                        220               21
12           13            17447                         32                6

C:\Users\zhu92\Coding\diversampling\undersampling.py:150: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  info_box = info_box.append({'cluster no.': int(cat), 'Sample counts': int(cat_arr.shape[0]), 'Random U-sampled counts': seed_num}, ignore_index=True)


counts
cat  label        
0.0  0       21699
     1           8
1.0  0       22905
     1          37
2.0  0       21039
     1           7
3.0  0       11798
     1         211
4.0  0       17081
     1          30
5.0  0       12907
     1          44
6.0  0       31058
     1           7
7.0  0       21278
     1          32
8.0  0       26181
     1          43
9.0  0       23528
     1           9
10.0 0       15395
11.0 0       14511
     1          37
12.0 0       27488
     1          21
13.0 0       17447
     1           6

In [11]:
usampling.array_merge    #sample data array with x, y, and cluster label
usampling.tar_cat_list    #a list of cluster no. with minority type of sample
usampling.free_cat_list    #a list of cluster no. without minority type of sample
usampling.array_usampled    #under-sampling outcome for data from clusters in tar_cat_list
usampling.array_random_usampled    #under-sampling outcome for data from clusters in free_cat_list
usampling.usampling_info_df    #CondensedNearestNeighbour under-sampling stats restults. This table will show while a under_sampling instance is initialized.
display(usampling.random_usampling_info_df)    #random under-sampling stats results

cluster no.  Majority counts  U-sampled Majority counts  Minority counts
0             0            21699                         22                8
1             1            22905                        240               37
2             2            21039                         98                7
3             3            11798                        467              211
4             4            17081                         94               30
5             5            12907                         91               44
6             6            31058                         63                7
7             7            21278                        136               32
8             8            26181                        198               43
9             9            23528                         19                9
10           11            14511                        143               37
11           12            27488                        220               21
12           13            17447                         32                6

cluster no.  Sample counts  Random U-sampled counts
0         10.0        15395.0                    770.0

In [12]:
display(usampling.array_under_sampled_final)    #final sample set after under-sampling
usampling.final_stats()    #sample balance stats of final dataset

array([[-0.03563816713146186, 0.1945684861499387, 0.032719059820408854,
        ..., 0.014521279289383992, 0.07116011875827323, 0.0],
       [-0.11875479930576734, 0.14848527183648302, 0.1736730967096466,
        ..., -0.017160938264018866, -0.029850358797876703, 0.0],
       [-0.14968437724947858, 0.21585622504492077, -0.1439603290605948,
        ..., 0.04155206647734584, -0.02541533494309665, 0.0],
       ...,
       [0.1304578083993906, -0.04575303468834262, -0.07370816851415178,
        ..., -0.00518756833449737, 0.021288576290441383, 0],
       [0.22051040160660404, -0.18292012199446392, -0.07668498127921021,
        ..., -0.009201056798783054, 0.027971478372661677, 0],
       [0.04882192122987833, -0.21379328717504012, 0.13499952715933078,
        ..., -0.00888171526005611, 0.05215651737020422, 0]], dtype=object)

Sample number: 3085
Minority sample number: 492.0
Majority sample number: 2593.0
Neg-Pos sample ratio: 18.974%


### Neg-Pos sample rate raised from 0.173% to 18.974%